language: python
python:
  - 3.6
  - 3.7

install:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock

script:
#  - coverage run --source=slumber setup.py test
  - pytest tests --junitxml=test_reports/icalendar.xml

#after_success:
#  - coveralls

notifications:
  slack:
    - garymcwilliams:RnFlaOcjeWPN1kIPOrQkLDDV
  email:
    - garymcwilliams@gmail.com
  webhooks:
    - https://www.travisbuddy.com/
