language: python
script:
  - make init ci

jobs:
  include:
    - stage: test
      python: 3.6
      script:
        - make init ci
    - stage: test
      python: 3.7
      script:
        - make init ci
      dist: xenial
      sudo: true     
    - stage: coverage
      python: 3.6
      script:
        - make init coverage
