language: python
python:
script:
  - "3.6"
  - "3.7-dev"

jobs:
  include:
    - stage: test
      script:
        - make ci
      python: '3.6'
    - stage: test
      script:
        - make ci
      python: '3.7'
      dist: xenial
      sudo: true     
    - stage: coverage
      python: 3.6
      script:
        - make coverage
