name: Python Coverage Workflow
on:
  push:
    branches:
      - 'master'
      - 'develop'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          pytest tests --cov=./ --cov-report=xml
          ls -al
          ls -al tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.codecov_token }}
          file: ./coverage.xml
          flags: unittests